### ISSUE TITLE
 Error Required field missing imageId

### ISSUE THREAD

**Issue by im663** [11k/dockerstiny#1]
After successful installation of the docker image, attempting to upload any sort of image to flairs/emotes/ or editing Themes results in ` Error Required field missing imageId` or ` Error Required field missing label`.

**Comment by tylerlevee** [comment]
Confirming this error, the chat doesn't function properly and uploading emotes/flairs fails. @11k please advise.

**Comment by 11k** [comment]
This error happens when the destination folder for image uploads doesn't exist (`website/static/emotes/` for emotes and `website/static/flairs/` for flairs). I submitted [a PR on destinygg/website](https://github.com/destinygg/website/pull/255) that simply creates the folder if it's missing when you upload an image. In the meantime, just create it manually to fix things.

As for chat not functioning properly, please create a new issue with a little more detail. 😁

**Comment by im663** [comment]
Sorry for the late update, just saw this issue update. After doing this, when attempting to impersonate admin, I get the following error message:

`
Fatal error: Uncaught UnexpectedValueException: The stream or file "/www/www.destiny.gg/log/web.log" could not be opened in append mode: failed to open stream: Permission denied in /www/www.destiny.gg/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110 Stack trace: #0 /www/www.destiny.gg/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array) #1 /www/www.destiny.gg/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /www/www.destiny.gg/vendor/monolog/monolog/src/Monolog/Logger.php(712): Monolog\Logger->addRecord(400, 'The stream or f...', Array) #3 /www/www.destiny.gg/lib/Destiny/Common/Log.php(30): Monolog\Logger->error('The stream or f...', Array) #4 /www/www.destiny.gg/public/index.php(56): Destiny\Common\Log::error('The stream or f...') #5 {main} thrown in /www/www.destiny.gg/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 110`

**Comment by im663** [comment]
Furthermore, when attempting to upload emotes or flairs, I still get the same error after creating the folders.

The docker-compose spits out this error:
`nginx_1    | 2021/05/25 05:06:33 [error] 20#20: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  move_uploaded_file(/www/www.destiny.gg/static/emotes/60ac85d93e4f6.png): failed to open stream: Permission denied in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 146PHP message: PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpE1xc57' to '/www/www.destiny.gg/static/emotes/60ac85d93e4f6.png' in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 146PHP message: PHP Notice:  Undefined index: label in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 31PHP message: PHP Notice:  Undefined index: name in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 32PHP message: PHP Notice:  Undefined index: hash in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 33PHP message: PHP Notice:  Undefined index: size in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 34PHP message: PHP Notice:  Undefined index: type in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 35PHP message: PHP Notice:  Undefined index: width in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 36PHP message: PHP Notice:  Undefined index: height in /www/www.destiny.gg/lib/Destiny/Common/Images/ImageService.php on line 37PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/www/www.destiny.gg/log/web.log" could not be opened in append mode: failed to open stream: Permission denied in /www/www.destiny.gg/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110
`

**Comment by im663** [comment]
Played around this this, ended up running `sudo chmod 0777 -R website/` and this fixed the error.

**Comment by im663** [comment]
Assuming I'm dumb and just the /flairs and /emotes folders need to have 0777 permissions.
